name: Compile C++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: name
      shell: bash
      run: echo $(pwd)
    - name: compile
      shell: bash
      run: echo $(git ls-files);
           chmod +x compile.sh;
           bash compile.sh
