name: Compile C++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: name
      shell: bash
      run: echo $(ls ${{github.workspace}})
    - name: compile
      shell: bash
      run: bash ${{github.workspace}}/compile.sh
