name: Compile C++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.73.0
          # OPTIONAL: Specify a platform version
          platform_version: 22.04


      # NOTE: If a boost version matching all requirements cannot be found,
      # this build step will fail
    - name: dependencies
      shell: bash
      run: apt install libboost-all-dev
    - name: compile
      shell: bash
      
      run: chmod +x compile.sh;
           bash compile.sh
