name: Compile C++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: name
      shell: bash
      run: echo $(pwd)
    - name: compile
      shell: bash
      run: chmod +x compile.sh;
           bash compile.sh
